small test

diff --git a/archivers/Makefile b/archivers/Makefile
--- a/archivers/Makefile
+++ b/archivers/Makefile
@@ -1,153 +1,136 @@
-#*************************************************************************
-#  Sequential Online Archiving of Objective Vectors
-#
-VERSION=1.1
-#                          Copyright (c) 2011
-#         Manuel Lopez-Ibanez <manuel.lopez-ibanez@ulb.ac.be>
-#             Joshua Knowles <j.knowles@manchester.ac.uk>
-#                 Marco Laumanns <mlm@zurich.ibm.com>
-#
-# This program is free software (software libre); you can redistribute
-# it and/or modify it under the terms of the GNU General Public License
-# as published by the Free Software Foundation; either version 2 of the
-# License, or (at your option) any later version.
-#
-# This program is distributed in the hope that it will be useful, but
-# WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
-# General Public License for more details.
-#
-# You should have received a copy of the GNU General Public License
-# along with this program; if not, you can obtain a copy of the GNU
-# General Public License at http://www.gnu.org/copyleft/gpl.html
-#
-# IMPORTANT NOTE: Please be aware that the fact that this program is
-# released as Free Software does not excuse you from scientific
-# propriety, which obligates you to give appropriate credit! If you
-# write a scientific paper describing research that made substantive use
-# of this program, it is your obligation as a scientist to (a) mention
-# the fashion in which this software was used in the Methods section;
-# (b) mention the algorithm in the References section. The appropriate
-# citation is:
-# 
-#     M. Lopez-Ibanez, J. Knowles, and M. Laumanns. On Sequential
-#     Online Archiving of Objective Vectors. In R. Takahashi et al., 
-#     editors, Evolutionary Multi-criterion Optimization (EMO 2011),
-#     volume 6576 of Lecture Notes in Computer Science, pages 46-60.
-#     Springer, Heidelberg, Germany, 2011.
-# 
-# Moreover, as a personal note, I would appreciate it if you would email
-# manuel.lopez-ibanez@ulb.ac.be with citations of papers referencing this
-# work so I can mention them to my funding agent and tenure committee.
-#
-# ----------------------------------------------------------------------
-#
-# Relevant literature:
-#
-# [1] M. Lopez-Ibanez, J. Knowles, and M. Laumanns. On Sequential
-#     Online Archiving of Objective Vectors. In R. Takahashi et al., 
-#     editors, Evolutionary Multi-criterion Optimization (EMO 2011),
-#     volume 6576 of Lecture Notes in Computer Science, pages 46-60.
-#     Springer, Heidelberg, Germany, 2011.
-#
-#*************************************************************************
+# ============================================================================
+#  Sequential Online Archiving of Objective Vectors (top-level Makefile)
+# ============================================================================
 
-DEBUG ?= 1
+PROJECT      := archiver
+VERSION      := 1.1
+DEBUG        ?= 1
+VARIANT      ?= 4
 
-## Do we have svnversion?
-ifeq ($(shell sh -c 'which svnversion 1> /dev/null 2>&1 && echo y'),y)
-  ## Is this a working copy?
-  ifneq ($(shell sh -c 'LC_ALL=C svnversion -n .'),exported)
-	$(shell sh -c 'svnversion -n . > svn_version')
-  endif
+CC           ?= gcc-13
+CXX          ?= g++-13
+AR           ?= ar
+RM           ?= rm -f
+
+BINDIR       := bin
+OBJDIR       := build
+TARGET       := $(BINDIR)/$(PROJECT)
+
+# --------------------------------------------------------------------------
+# Sources
+# --------------------------------------------------------------------------
+BASE_CPP_SRCS := archiver.cpp Archive.cpp Solution.cpp
+BASE_C_SRCS   := mt.c rng.c
+
+SHARED_SRCS  := hv.c avl.c 
+SHARED_HDRS  := hv.h avl.h libmoocore-config.h
+
+# --------------------------------------------------------------------------
+# Path to libmoocore (symlink inside archiver -> ../c)
+# --------------------------------------------------------------------------
+LIBMOOCORE_DIR := libmoocore
+LIBMOOCORE_SO  := $(LIBMOOCORE_DIR)/libmoocore.so
+MOO_OUT        := $(BINDIR)/libmoocore.so
+
+# --------------------------------------------------------------------------
+# USE_LIBMOOCORE:
+#   0 = use shared lib from libmoocore (default)
+#   1 = use bundled .c files from archiver dir
+# --------------------------------------------------------------------------
+USE_LIBMOOCORE ?= 0
+
+ifeq ($(USE_LIBMOOCORE),0)
+    $(info Using shared library from $(LIBMOOCORE_DIR))
+    SRCS := $(BASE_CPP_SRCS) $(BASE_C_SRCS)
+    CPPFLAGS += -DUSE_SHARED_LIB=1 -DUSE_LIBMOOCORE_HEADERS=1
+    CPPFLAGS += -I$(LIBMOOCORE_DIR) -I.
+    LDLIBS   += -L$(BINDIR) -lmoocore -Wl,-rpath,$(BINDIR)
+    EXTRA_DEPS := $(MOO_OUT)
+
+else ifeq ($(USE_LIBMOOCORE),1)
+    $(info Using bundled C sources from archiver dir)
+    SRCS := $(BASE_CPP_SRCS) $(BASE_C_SRCS) $(SHARED_SRCS)
+    CPPFLAGS += -DUSE_SHARED_LIB=0 -DUSE_LIBMOOCORE_HEADERS=0
+    CPPFLAGS += -I. -I$(LIBMOOCORE_DIR)
+    EXTRA_DEPS :=
+
+else
+    $(error Invalid USE_LIBMOOCORE value: $(USE_LIBMOOCORE))
 endif
 
-## Set version information:
-SVN_REV = $(shell sh -c 'cat svn_version 2> /dev/null')
+# --------------------------------------------------------------------------
+# Objects (derived automatically from SRCS)
+# --------------------------------------------------------------------------
+OBJS := $(patsubst %.cpp,$(OBJDIR)/%.o,$(filter %.cpp,$(SRCS))) \
+        $(patsubst %.c,$(OBJDIR)/%.o,$(filter %.c,$(SRCS)))
 
-MAIN = archiver
-SRCS = archiver.cpp Archive.cpp Solution.cpp rng.c mt.c
-HDRS = *.h
-OBJS = $(patsubst %.cpp,%.o,$(patsubst %.c,%.o,$(SRCS)))
+# --------------------------------------------------------------------------
+# Compiler flags
+# --------------------------------------------------------------------------
+CPPFLAGS    += -DVARIANT=$(VARIANT) -DDEBUG=$(DEBUG) -DVERSION='"$(VERSION)"'
+CPPFLAGS    += -MMD -MP
+COMMON_WARN := -Wall -Wextra -Wpedantic
 
-DIST_SRC_FILES = Makefile Makefile.lib \
-		 README LICENSE PISA_LICENSE.txt \
-		 svn_version \
-		 $(SRCS) $(HDRS) \
-		 $(HV_SRCS) $(HV_HDRS)
-
-DIST_SRC       = archivers-$(VERSION)-src
-
-################################################################################
-## Configure the compiler / linker:
-
-## Global list of CPP flags
-CPPFLAGS = -D DEBUG=$(DEBUG) -D VERSION='"$(VERSION)"'
-
-ifneq ($(DEBUG), 0)
-DEBUGFLAGS = -g3
-CPPFLAGS += -DMALLOC_CHECK_=3
+ifeq ($(DEBUG),0)
+  DEBUGFLAGS := -O2
+else
+  DEBUGFLAGS := -g3 -DMALLOC_CHECK_=3
 endif
 
-CXXFLAGS = $(DEBUGFLAGS) -Wall -Wextra
-CFLAGS = $(CXXFLAGS)
+CFLAGS   += $(DEBUGFLAGS) $(COMMON_WARN)
+CXXFLAGS += $(DEBUGFLAGS) $(COMMON_WARN)
 
-.PHONY: all clean dist test default
+# --------------------------------------------------------------------------
+# Build rules
+# --------------------------------------------------------------------------
+.PHONY: all clean help print-sources
 
+all: $(TARGET)
 
+help:
+	@echo "Targets: all, clean, print-sources"
+	@echo "Vars: DEBUG=1|0 VARIANT=<int> USE_C_CODE=<0|1|2> CC/CXX BINDIR OBJDIR"
+	@echo "  USE_C_CODE=0 : shared lib from libmoocore (default)"
+	@echo "  USE_C_CODE=1 : compile sources from libmoocore/"
+	@echo "  USE_C_CODE=2 : compile bundled hv.c/avl.c from archiver/"
 
-BINDIR = bin
-LIBMOOCORE_SO = $(BINDIR)/libmoocore.so
-MAIN_EXE = $(BINDIR)/archiver
+print-sources:
+	@echo "SRCS = $(SRCS)"
+	@echo "OBJS = $(OBJS)"
 
-all: clean $(LIBMOOCORE_SO) $(MAIN_EXE)
+$(BINDIR) $(OBJDIR):
+	@mkdir -p $@
 
-$(BINDIR):
-	mkdir -p $(BINDIR)
+$(OBJDIR)/%.o: %.cpp
+	@mkdir -p $(dir $@)
+	@echo "Compiling C++ file: $< -> $@"
+	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $<
 
-$(LIBMOOCORE_SO): | $(BINDIR)
-	$(MAKE) -C libmoocore shlibs
-	cp libmoocore/libmoocore.so $(LIBMOOCORE_SO)
+$(OBJDIR)/%.o: %.c
+	@mkdir -p $(dir $@)
+	@echo "Compiling C file: $< -> $@"
+	$(CC) $(CPPFLAGS) $(CFLAGS) -c -o $@ $<
 
+$(OBJDIR)/%.o: $(LIBMOOCORE_DIR)/%.c
+	@mkdir -p $(dir $@)
+	@echo "Compiling C file from libmoocore: $< -> $@"
+	$(CC) $(CPPFLAGS) $(CFLAGS) -c -o $@ $<
+
+# Rule to ensure we have a shared library if using mode 0
+$(MOO_OUT): | $(BINDIR)
+	if [ ! -f "$(LIBMOOCORE_SO)" ]; then \
+		echo "libmoocore.so not found. Building in $(LIBMOOCORE_DIR)"; \
+		$(MAKE) -C $(LIBMOOCORE_DIR) shlibs || { echo "Failed to build libmoocore"; exit 1; }; \
+	fi
+	cp $(LIBMOOCORE_SO) $(MOO_OUT)
+
+# Main executable
+$(TARGET): $(OBJS) $(EXTRA_DEPS) | $(BINDIR)
+	@echo "Linking target: $@"
+	$(CXX) $(CXXFLAGS) $^ $(LDLIBS) -o $@
 
 clean:
-	$(call ECHO,---> Removing $(MAIN) <---)
-	@$(RM) $(MAIN)
-	$(call ECHO,---> Removing object files <---)
-	@$(RM) $(OBJS) $(HV_OBJS)
-	$(call ECHO,---> Removing $(HV_LIB) <---)
-	@$(RM) $(HV_LIB)
-	$(call ECHO,---> Removing backup files <---)
-	@$(RM) *~
-	$(call ECHO,---> Removing bin directory and its contents <---)
-	@rm -rf bin
+	@echo "Cleaning build directories: $(BINDIR) and $(OBJDIR)"
+	$(RM) -r $(BINDIR) $(OBJDIR)
 
-dist : all
-	@(rm -f ../$(DIST_SRC).tar.gz && mkdir -p ../$(DIST_SRC) \
-	&& rsync -rlpC --relative --exclude=.svn $(DIST_SRC_FILES) ../$(DIST_SRC)/ \
-	&& cd .. \
-	&& tar cf - $(DIST_SRC) | gzip -f9 > $(DIST_SRC).tar.gz \
-	&& rm -rf ./$(DIST_SRC)/* && rmdir ./$(DIST_SRC)/ \
-	&& echo "$(DIST_SRC).tar.gz created." && cd $(PWD) )
-
-#----------------------------------------------------------------------
-# Include actual HV code:
-include Makefile.lib
-
-$(MAIN_EXE): $(LIBMOOCORE_SO) $(OBJS) $(HV_LIB) | $(BINDIR)
-	$(call ECHO,---> Building $@ version $(VERSION) <---)
-	${CXX} ${CXXFLAGS} $^ -L$(BINDIR) -lmoocore -Wl,-rpath,$(BINDIR) -o $@
-
-#----------------------------------------------------------------------
-# Dependencies:
-archiver.o: archiver.cpp eApproxArchive.h eParetoArchive.h SPEA2Archive.h NSGA2Archive.h HVArchive.h AdaptiveGridArchive.h MultilevelGridArchive.h Random.h 
-
-Archive.o: Archive.cpp Archive.h
-
-Solution.o: Solution.cpp Solution.h
-
-mt.o: mt.c gsl_rng.h gsl_types.h
-
-rng.o : rng.c gsl_rng.h gsl_types.h
-
-
+-include $(OBJS:.o=.d)
